@baseUrl = http://localhost:5000

@urlPath= api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "652d3ba2a4a747939d76b7db",
  "postId": "653915eb4f44458e1968b875",
  "comment": "Testing email servise again",
  "profilePicture": "https://res.cloudinary.com/dux3dgz8f/image/upload/v1696862384/652410af86101ec8faa15dde"
}

###
GET {{baseUrl}}/{{urlPath}}/post/comments/653915eb4f44458e1968b875
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/653915eb4f44458e1968b875
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/653915eb4f44458e1968b875/653bc1d62251130a89f74635
Content-Type: application/json
Accept: application/json
withCredentials: true
