@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/6548fc7d155215ec1cc6beeb
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
