@baseUrl = http://localhost:5000

@urlPath= api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "652d3ba2a4a747939d76b7db",
  "postId": "653915eb4f44458e1968b875",
  "type": "happy",
  "previousReaction": "love",
  "postReactions": {"like": 0,"love": 0,"happy": 1,"wow": 0,"sad": 0,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/dux3dgz8f/image/upload/v1697464095/652d3f1ff50d2ce056967ab4"
}
